aibtcdev/aibtcdev-backend

- tools/alex.py
- tools/bitflow.py
- tools/lunarcrush.py
- tools/tools_factory.py
This updates the backend tools and adds some based on the Token Analyzer in `ai-agent-crew`.
There might be some others to add too like TX status, own wallet balance, etc.
Also tried to standardize the naming!
> Add missing tools

- .replit
- main.py
- requirements.txt
This should allow the app to pass the 5s health check then load the "heavier" routes with LLM calls after.
> Optimize app startup

- .env.example
- main.py
- requirements.txt
> Add LangTrace

- services/crew_services.py
Removed all the compiler agents and cleaned the code a bit.
> fix(crew_service): remove the compiler agents

- api/public_crews.py
- main.py
new endpoint for public crews.
> feat(api): new endpoint for public-crews

- .gitignore
- README.md
> :memo: Update readme

- tools/jing.py
Note: This is AI-assisted code as I'm learning the stack. Please review carefully for:
- Integration compatibility with Jing Cash agent tools
- Security considerations
- Production readiness
> add jing tools

- tools/dao.py
- tools/tools_factory.py
This pull request introduces a set of new tools for DAO (Decentralized Autonomous Organization) management in the `tools/dao.py` file and integrates them into the tool initialization process in `tools/tools_factory.py`. The most important changes include the addition of various deployment and operation tools for different DAO contracts.
New DAO tools added:
* [`tools/dao.py`](diffhunk://#diff-dde031525d542e66a8bbdd2643b796ecdc4b8e3342136323b1a7ffd9b9cdc029R1-R282): Added `ExecutorDeployTool`, `TreasuryDeployTool`, `TreasuryDepositTool`, `BankAccountDeployTool`, `MessagingDeployTool`, `MessagingSendTool`, `PaymentsDeployTool`, and `PaymentsAddResourceTool` classes to manage DAO contracts.
Integration of new DAO tools:
* [`tools/tools_factory.py`](diffhunk://#diff-2da76e75983df6709cee36d1f63 …
> :sparkles: Add DAO scripts to registry

- tools/faktory.py
It's not handling the arguments correctly, must simplify.
> Fix GetDaoTokens tool

- tools/dao_ext_action_proposals.py
*edit:* verified all dao tooling has coreect path
> Fix dao tooling desc v2

- tools/faktory.py
- tools/tools_factory.py
Updates for Faktory based on latest SDK
> Separate btc/stx buy tools

- tools/smartwallet.py
Some quick notes:
- contracts are designed to be 1:1 between owner (user) and agent (voter)
- contracts are designed to hold funds that can only be withdrawn by user
- contracts are designed to create, vote, and conclude aibtc dao proposals
> smart wallet deploy tool

- services/workflows/proposal_evaluation.py
- tools/dao_ext_action_proposals.py
- tools/dao_ext_timed_vault.py
- tools/faktory.py
- tools/tools_factory.py
Following aibtcdev/agent-tools-ts#119 there were quite a few updates that need to happen on the Python side next.
> Use latest contracts tooling

- tools/dao_ext_action_proposals.py
This adds the `dao_token_contract` as a required parameter to help with setting correct PC on transfers for:
- all action-proposal tools
- action-proposal conclude proposal tool
> Fix proposal post conditions

- tools/dao_ext_action_proposals.py
Quick fix to add new optional memo
> Update action proposal tooling

- docs/chainhook_service.md
- docs/runners.md
- docs/workflows.md
- services/workflows/base.py
- services/workflows/proposal_evaluation.py
- services/workflows/vector_preplan_react.py
- services/workflows/web_search.py
- Updated the `WebSearchCapability` mixin in `base.py` to use OpenAI's new Responses API instead of the Assistants API
- Integrated web search functionality into the proposal evaluation workflow
- Added proper error handling and fallbacks for web search results
- Switched from `web_browser` to `web_search_preview` tool type
- Updated response handling to match the new Responses API format
- Added search context size support (defaulting to "medium")
- Improved URL citation handling with the new metadata structure
- Added proper initialization chain for the mixin to handle multiple inheritance
The changes should be tested by:
1. Evaluating a proposal to ensure web search results are properly incorporated
2. Verifying the confidence scoring takes web search context into account
3. Checking …
> Search Functionality

- services/webhooks/chainhook/handlers/action_concluder_handler.py
Passed proposals: 🟩 {dao_name} PROPOSAL #{proposal_id}: PASSED 🟩
Failed proposals: 🟥 {dao_name} PROPOSAL #{proposal_id}: FAILED 🟥
> updated proposals titles

- tools/agent_account.py
- tools/agent_account_action_proposals.py
- tools/dao_ext_action_proposals.py
- tools/tools_factory.py
This PR updates the existing create/conclude proposal tools to use the new input format for direct agent wallets, as well as adds new agent account versions of create, vote, veto, and conclude.
> Agent account tool updates

- app/api/tools/agent_account.py
- app/api/tools/models.py
This updates the model for the new param in line with https://github.com/aibtcdev/aibtcdev-frontend/pull/444 and then passes it to the bun script for compatibility with https://github.com/aibtcdev/agent-tools-ts/pull/193 and https://github.com/aibtcdev/agent-tools-ts/pull/195.
> Fix contract approval type in API

- app/api/dao.py
- app/main.py
Added a new API endpoint `/api/dao/token_holders` that returns agent account contracts holding a specific DAO token, with advanced filtering capabilities based on DAO engagement metrics.
- **URL**: `GET /api/dao/token_holders`
- **Authentication**: Requires `X-API-Key` header with agent lookup API key
- **Primary Parameter**: `token_contract_principal` (required) - The DAO token contract to find holders for
- **Response**: JSON object with `holders` array containing agent account contract principals
- **Parameter**: `voted_in_last_proposals` (optional integer)
- **Description**: Filters to agents who voted in the last X proposals for the token's DAO
- **Logic**: Gets most recent N proposals chronologically, checks if agent voted in any of them
- **Use Case**: Identify actively engaged …
> Add DAO Token Holders API Endpoint with Engagement Filtering

- app/services/ai/simple_workflows/llm.py
> Add hardcoded OpenRouter headers to ChatOpenAI instances

- app/services/ai/simple_workflows/orchestrator.py
- app/services/ai/simple_workflows/prompts/evaluation_elonbtc.py
- app/services/infrastructure/job_management/tasks/dao_proposal_evaluation.py
if dao name matches then use the special prompts
> elonbtc sys prompt

- app/services/ai/simple_workflows/prompts/evaluation_elonbtc.py
v2, a bit stricter based on switch to `x-ai/grok-4-fast` as default LLM
> update elon prompt
